# Generated by Django 4.1.5 on 2023-01-12 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, verbose_name='category_name')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswerOptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('TF', 'True or False')], max_length=3, verbose_name='question_answer_option_type')),
                ('option1', models.CharField(max_length=100, verbose_name='option1')),
                ('option2', models.CharField(max_length=100, verbose_name='option2')),
                ('option3', models.CharField(blank=True, max_length=100, verbose_name='option3')),
                ('option4', models.CharField(blank=True, max_length=100, verbose_name='option4')),
                ('correct_option', models.IntegerField(verbose_name='correct_option')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_description', models.CharField(max_length=200, verbose_name='question_description')),
                ('points', models.IntegerField(verbose_name='points')),
                ('answer_option_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QZ_Star.questionansweroptiontype')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QZ_Star.category')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=30, verbose_name='quiz_name')),
                ('is_active', models.BooleanField(verbose_name='is_active')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QZ_Star.category', verbose_name='category_id')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_question_in_quiz', models.BooleanField(verbose_name='active_question')),
                ('question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QZ_Star.questionbank')),
                ('quiz_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QZ_Star.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizUserScoreSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_selected', models.IntegerField(choices=[(1, 'option1/True'), (2, 'option2/False'), (3, 'option3'), (4, 'option4')], verbose_name='option_selected')),
                ('score', models.IntegerField(verbose_name='score')),
                ('quiz_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QZ_Star.quiz')),
                ('quiz_questions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QZ_Star.quizquestions')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizUserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_score', models.IntegerField(verbose_name='user_score')),
                ('quiz_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QZ_Star.quiz')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
