# Generated by Django 4.1.5 on 2023-01-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QZ_Star', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionansweroptiontype',
            name='option3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='option3'),
        ),
        migrations.AlterField(
            model_name='questionansweroptiontype',
            name='option4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='option4'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='active_question_in_quiz',
            field=models.BooleanField(default=True, verbose_name='active_question'),
        ),
    ]
