# Generated by Django 4.1.5 on 2023-01-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QZ_Star', '0002_alter_questionansweroptiontype_option3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='is_anonymous'),
        ),
    ]
